services:
  - type: web
    name: legal-case-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    
  - type: static
    name: legal-case-finder-frontend
    buildCommand: echo "Static site build"
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" 